package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * InspeccionVehiculo generated by hbm2java
 */
public class InspeccionVehiculo  implements java.io.Serializable {


     private String id;
     private String id_empresa;
     private String idVehiculo;
     private String chasis;
     private String referencia;
     private Date fechaInspeccion;
     private String serieGomas;
     private String nivelCombustible;
     private String idMecanico;
     private String supervisor;
     private String estado;
     private Date fechaInsercion;
     private String usuarioInsercion;
     private Date fechaActualizacion;
     private String usuarioActualizacion;
     private Long trOrigen;
     private String observaciones;
     private String idAsesor;
     private String idCliente;
     private String kilometraje;

    public InspeccionVehiculo() {
    }

	
    public InspeccionVehiculo(String id) {
        this.id = id;
    }
    
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getChasis() {
        return this.chasis;
    }
    
    public void setChasis(String chasis) {
        this.chasis = chasis;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public Date getFechaInspeccion() {
        return this.fechaInspeccion;
    }
    
    public void setFechaInspeccion(Date fechaInspeccion) {
        this.fechaInspeccion = fechaInspeccion;
    }
    public String getSerieGomas() {
        return this.serieGomas;
    }
    
    public void setSerieGomas(String serieGomas) {
        this.serieGomas = serieGomas;
    }
    public String getNivelCombustible() {
        return this.nivelCombustible;
    }
    
    public void setNivelCombustible(String nivelCombustible) {
        this.nivelCombustible = nivelCombustible;
    }
    public String getIdMecanico() {
        return this.idMecanico;
    }
    
    public void setIdMecanico(String idMecanico) {
        this.idMecanico = idMecanico;
    }
    public String getSupervisor() {
        return this.supervisor;
    }
    
    public void setSupervisor(String supervisor) {
        this.supervisor = supervisor;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }
    
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }
    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }
    
    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }
    
    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }
    public Long getTrOrigen() {
        return this.trOrigen;
    }
    
    public void setTrOrigen(Long trOrigen) {
        this.trOrigen = trOrigen;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getIdAsesor() {
        return this.idAsesor;
    }
    
    public void setIdAsesor(String idAsesor) {
        this.idAsesor = idAsesor;
    }
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * @return the id_empresa
     */
    public String getId_empresa() {
        return id_empresa;
    }

    /**
     * @param id_empresa the id_empresa to set
     */
    public void setId_empresa(String id_empresa) {
        this.id_empresa = id_empresa;
    }

    /**
     * @return the kilometraje
     */
    public String getKilometraje() {
        return kilometraje;
    }

    /**
     * @param kilometraje the kilometraje to set
     */
    public void setKilometraje(String kilometraje) {
        this.kilometraje = kilometraje;
    }




}


