package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoTransaccion generated by hbm2java
 */
public class TipoTransaccion  implements java.io.Serializable {


     private String id;
     private String id_empresa;
     private String descripcion;
     private String estado;
     private Date fechaInsercion;
     private String usuarioInsercion;
     private Date fechaActualizacion;
     private String usuarioActualizacion;
     private Long secuencia;
     private Character origen;
     private Character operadorInventario;
     private Boolean afectaDoc;
     private Boolean contabiliza;
     private String idTipoDoc;
     private Boolean aplicaNcf;
     private String activo;
     private Boolean activoDeprec;
     private Boolean tipoFt;
     private Long trOrigen;
    

    public TipoTransaccion() {
    }


    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }
    
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }
    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }
    
    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }
    
    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }
    public Long getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(Long secuencia) {
        this.secuencia = secuencia;
    }
    public Character getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(Character origen) {
        this.origen = origen;
    }
    public Character getOperadorInventario() {
        return this.operadorInventario;
    }
    
    public void setOperadorInventario(Character operadorInventario) {
        this.operadorInventario = operadorInventario;
    }
    public Boolean getAfectaDoc() {
        return this.afectaDoc;
    }
    
    public void setAfectaDoc(Boolean afectaDoc) {
        this.afectaDoc = afectaDoc;
    }
    public Boolean getContabiliza() {
        return this.contabiliza;
    }
    
    public void setContabiliza(Boolean contabiliza) {
        this.contabiliza = contabiliza;
    }
    public String getIdTipoDoc() {
        return this.idTipoDoc;
    }
    
    public void setIdTipoDoc(String idTipoDoc) {
        this.idTipoDoc = idTipoDoc;
    }
    public Boolean getAplicaNcf() {
        return this.aplicaNcf;
    }
    
    public void setAplicaNcf(Boolean aplicaNcf) {
        this.aplicaNcf = aplicaNcf;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Boolean getActivoDeprec() {
        return this.activoDeprec;
    }
    
    public void setActivoDeprec(Boolean activoDeprec) {
        this.activoDeprec = activoDeprec;
    }
    public Boolean getTipoFt() {
        return this.tipoFt;
    }
    
    public void setTipoFt(Boolean tipoFt) {
        this.tipoFt = tipoFt;
    }
    public Long getTrOrigen() {
        return this.trOrigen;
    }
    
    public void setTrOrigen(Long trOrigen) {
        this.trOrigen = trOrigen;
    }
  
    /**
     * @return the id_empresa
     */
    public String getId_empresa() {
        return id_empresa;
    }

    /**
     * @param id_empresa the id_empresa to set
     */
    public void setId_empresa(String id_empresa) {
        this.id_empresa = id_empresa;
    }




}


