package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String id;
     private String id_empresa;
     private String chasis;
     private String idTipoVehiculo;
     private String idMarca;
     private String idModelo;
     private String idEstilo;
     private String nota;
     private String color;
     private String colorInterior;
     private String ano;
     private String fechaCompra;
     private int filaAsiento;
     private int cantPuerta;
     private String idCombustible;
     private String idTraccion;
     private String cilindraje;
     private String millaje;
     private String kilometraje;
     private String referencia;
     private String idMoneda;
     private String precioCompra;
     private String placa;
     private String llamar;
     private String idCliente;
     private String estado;
     private Date fechaInsercion;
     private String usuarioInsercion;
     private Date fechaActualizacion;
     private String usuarioActualizacion;
     private String trOrigen;
     private String idTransmision;
     private String origenFab;
     private String origenComp;
     private String condicionVehi;
     private String carga;
     private String pasajeros;
     private int cilindros;
     private String idEntGarantia;
     private String kmGarantia;
     private String tiempoGarantia;
     private String garantia;
     private String notasGarantia;
     private String idUso;
     private String noVelocidades;
     private String vmUbicacion;
     private String idTipoVehDgii;
     private String modeloSegunDgii;
     private int secuenciaEntrada;
     private String desc_modelo;
     private String desc_marca;
     private String desc_estilo;
     private String idIntermediario;
     private String nombreIntermediario;
     private String ficha;
     private String nombre;
     private String telefono;
     private String ult_fecha_llamado;
     private String cantidad_dias_llamar;
     private String origen_fab;
     private String id_origen_comp;
     private String celular;
     private String estadoVeh;
     

    public Vehiculo() {
    }

	

   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getIdTipoVehiculo() {
        return this.idTipoVehiculo;
    }
    
    public void setIdTipoVehiculo(String idTipoVehiculo) {
        this.idTipoVehiculo = idTipoVehiculo;
    }
    public String getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(String idMarca) {
        this.idMarca = idMarca;
    }
    public String getIdModelo() {
        return this.idModelo;
    }
    
    public void setIdModelo(String idModelo) {
        this.idModelo = idModelo;
    }
    public String getIdEstilo() {
        return this.idEstilo;
    }
    
    public void setIdEstilo(String idEstilo) {
        this.idEstilo = idEstilo;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getColorInterior() {
        return this.colorInterior;
    }
    
    public void setColorInterior(String colorInterior) {
        this.colorInterior = colorInterior;
    }
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }
    public String getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(String fechaCompra) {
        this.fechaCompra = fechaCompra;
    }

    public String getIdCombustible() {
        return this.idCombustible;
    }
    
    public void setIdCombustible(String idCombustible) {
        this.idCombustible = idCombustible;
    }
    public String getIdTraccion() {
        return this.idTraccion;
    }
    
    public void setIdTraccion(String idTraccion) {
        this.idTraccion = idTraccion;
    }
    public String getCilindraje() {
        return this.cilindraje;
    }
    
    public void setCilindraje(String cilindraje) {
        this.cilindraje = cilindraje;
    }
    public String getMillaje() {
        return this.millaje;
    }
    
    public void setMillaje(String millaje) {
        this.millaje = millaje;
    }
    public String getKilometraje() {
        return this.kilometraje;
    }
    
    public void setKilometraje(String kilometraje) {
        this.kilometraje = kilometraje;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getIdMoneda() {
        return this.idMoneda;
    }
    
    public void setIdMoneda(String idMoneda) {
        this.idMoneda = idMoneda;
    }
    public String getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(String precioCompra) {
        this.precioCompra = precioCompra;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getLlamar() {
        return this.llamar;
    }
    
    public void setLlamar(String llamar) {
        this.llamar = llamar;
    }
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }
    
    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }
    
    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }
    public String getTrOrigen() {
        return this.trOrigen;
    }
    
    public void setTrOrigen(String trOrigen) {
        this.trOrigen = trOrigen;
    }
    public String getIdTransmision() {
        return this.idTransmision;
    }
    
    public void setIdTransmision(String idTransmision) {
        this.idTransmision = idTransmision;
    }
    public String getOrigenFab() {
        return this.origenFab;
    }
    
    public void setOrigenFab(String origenFab) {
        this.origenFab = origenFab;
    }
    public String getOrigenComp() {
        return this.origenComp;
    }
    
    public void setOrigenComp(String origenComp) {
        this.origenComp = origenComp;
    }
    public String getCondicionVehi() {
        return this.condicionVehi;
    }
    
    public void setCondicionVehi(String condicionVehi) {
        this.condicionVehi = condicionVehi;
    }
 
    public String getCarga() {
        return this.carga;
    }
    
    public void setCarga(String carga) {
        this.carga = carga;
    }

    public int getCilindros() {
        return this.cilindros;
    }
    
    public void setCilindros(int cilindros) {
        this.cilindros = cilindros;
    }
    public String getIdEntGarantia() {
        return this.idEntGarantia;
    }
    
    public void setIdEntGarantia(String idEntGarantia) {
        this.idEntGarantia = idEntGarantia;
    }
    public String getKmGarantia() {
        return this.kmGarantia;
    }
    
    public void setKmGarantia(String kmGarantia) {
        this.kmGarantia = kmGarantia;
    }
    public String getTiempoGarantia() {
        return this.tiempoGarantia;
    }
    
    public void setTiempoGarantia(String tiempoGarantia) {
        this.tiempoGarantia = tiempoGarantia;
    }
 
    public String getNotasGarantia() {
        return this.notasGarantia;
    }
    
    public void setNotasGarantia(String notasGarantia) {
        this.notasGarantia = notasGarantia;
    }
    public String getIdUso() {
        return this.idUso;
    }
    
    public void setIdUso(String idUso) {
        this.idUso = idUso;
    }
    public String getNoVelocidades() {
        return this.noVelocidades;
    }
    
    public void setNoVelocidades(String noVelocidades) {
        this.noVelocidades = noVelocidades;
    }
    public String getVmUbicacion() {
        return this.vmUbicacion;
    }
    
    public void setVmUbicacion(String vmUbicacion) {
        this.vmUbicacion = vmUbicacion;
    }
    public String getIdTipoVehDgii() {
        return this.idTipoVehDgii;
    }
    
    public void setIdTipoVehDgii(String idTipoVehDgii) {
        this.idTipoVehDgii = idTipoVehDgii;
    }
    public String getModeloSegunDgii() {
        return this.modeloSegunDgii;
    }
    
    public void setModeloSegunDgii(String modeloSegunDgii) {
        this.modeloSegunDgii = modeloSegunDgii;
    }

    /**
     * @return the id_empresa
     */
    public String getId_empresa() {
        return id_empresa;
    }

    /**
     * @param id_empresa the id_empresa to set
     */
    public void setId_empresa(String id_empresa) {
        this.id_empresa = id_empresa;
    }

    /**
     * @return the chasis
     */
    public String getChasis() {
        return chasis;
    }

    /**
     * @param chasis the chasis to set
     */
    public void setChasis(String chasis) {
        this.chasis = chasis;
    }

    /**
     * @return the filaAsiento
     */
    public int getFilaAsiento() {
        return filaAsiento;
    }

    /**
     * @param filaAsiento the filaAsiento to set
     */
    public void setFilaAsiento(int filaAsiento) {
        this.filaAsiento = filaAsiento;
    }

    /**
     * @return the cantPuerta
     */
    public int getCantPuerta() {
        return cantPuerta;
    }

    /**
     * @param cantPuerta the cantPuerta to set
     */
    public void setCantPuerta(int cantPuerta) {
        this.cantPuerta = cantPuerta;
    }

    /**
     * @return the pasajeros
     */
    public String getPasajeros() {
        return pasajeros;
    }

    /**
     * @param pasajeros the pasajeros to set
     */
    public void setPasajeros(String pasajeros) {
        this.pasajeros = pasajeros;
    }

    /**
     * @return the fechaInsercion
     */
    public Date getFechaInsercion() {
        return fechaInsercion;
    }

    /**
     * @param fechaInsercion the fechaInsercion to set
     */
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }

    /**
     * @return the garantia
     */
    public String getGarantia() {
        return garantia;
    }

    /**
     * @param garantia the garantia to set
     */
    public void setGarantia(String garantia) {
        this.garantia = garantia;
    }

    /**
     * @return the secuenciaEntrada
     */
    public int getSecuenciaEntrada() {
        return secuenciaEntrada;
    }

    /**
     * @param secuenciaEntrada the secuenciaEntrada to set
     */
    public void setSecuenciaEntrada(int secuenciaEntrada) {
        this.secuenciaEntrada = secuenciaEntrada;
    }

    /**
     * @return the desc_modelo
     */
    public String getDesc_modelo() {
        return desc_modelo;
    }

    /**
     * @param desc_modelo the desc_modelo to set
     */
    public void setDesc_modelo(String desc_modelo) {
        this.desc_modelo = desc_modelo;
    }

    /**
     * @return the desc_marca
     */
    public String getDesc_marca() {
        return desc_marca;
    }

    /**
     * @param desc_marca the desc_marca to set
     */
    public void setDesc_marca(String desc_marca) {
        this.desc_marca = desc_marca;
    }

    /**
     * @return the desc_estilo
     */
    public String getDesc_estilo() {
        return desc_estilo;
    }

    /**
     * @param desc_estilo the desc_estilo to set
     */
    public void setDesc_estilo(String desc_estilo) {
        this.desc_estilo = desc_estilo;
    }

    /**
     * @return the idIntermediario
     */
    public String getIdIntermediario() {
        return idIntermediario;
    }

    /**
     * @param idIntermediario the idIntermediario to set
     */
    public void setIdIntermediario(String idIntermediario) {
        this.idIntermediario = idIntermediario;
    }

    /**
     * @return the nombreIntermediario
     */
    public String getNombreIntermediario() {
        return nombreIntermediario;
    }

    /**
     * @param nombreIntermediario the nombreIntermediario to set
     */
    public void setNombreIntermediario(String nombreIntermediario) {
        this.nombreIntermediario = nombreIntermediario;
    }

    /**
     * @return the ficha
     */
    public String getFicha() {
        return ficha;
    }

    /**
     * @param ficha the ficha to set
     */
    public void setFicha(String ficha) {
        this.ficha = ficha;
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return the telefono
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * @param telefono the telefono to set
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * @return the ult_fecha_llamado
     */
    public String getUlt_fecha_llamado() {
        return ult_fecha_llamado;
    }

    /**
     * @param ult_fecha_llamado the ult_fecha_llamado to set
     */
    public void setUlt_fecha_llamado(String ult_fecha_llamado) {
        this.ult_fecha_llamado = ult_fecha_llamado;
    }

    /**
     * @return the cantidad_dias_llamar
     */
    public String getCantidad_dias_llamar() {
        return cantidad_dias_llamar;
    }

    /**
     * @param cantidad_dias_llamar the cantidad_dias_llamar to set
     */
    public void setCantidad_dias_llamar(String cantidad_dias_llamar) {
        this.cantidad_dias_llamar = cantidad_dias_llamar;
    }

    /**
     * @return the origen_fab
     */
    public String getOrigen_fab() {
        return origen_fab;
    }

    /**
     * @param origen_fab the origen_fab to set
     */
    public void setOrigen_fab(String origen_fab) {
        this.origen_fab = origen_fab;
    }

    /**
     * @return the id_origen_comp
     */
    public String getId_origen_comp() {
        return id_origen_comp;
    }

    /**
     * @param id_origen_comp the id_origen_comp to set
     */
    public void setId_origen_comp(String id_origen_comp) {
        this.id_origen_comp = id_origen_comp;
    }

    /**
     * @return the celular
     */
    public String getCelular() {
        return celular;
    }

    /**
     * @param celular the celular to set
     */
    public void setCelular(String celular) {
        this.celular = celular;
    }

    /**
     * @return the estadoVeh
     */
    public String getEstadoVeh() {
        return estadoVeh;
    }

    /**
     * @param estadoVeh the estadoVeh to set
     */
    public void setEstadoVeh(String estadoVeh) {
        this.estadoVeh = estadoVeh;
    }




}


