package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VehiculoDocumento generated by hbm2java
 */
public class VehiculoDocumento  implements java.io.Serializable {


     private String id_vehiculo;
     private String id_empresa;
     private String id_tipo_trans;
     private String rutaDocumento;
     private String id_documento;
     private String nota;
     private String estado;
     private Date fechaInsercion;
     private String usuarioInsercion;
     private Date fechaActualizacion;
     private String usuarioActualizacion;
     private BigDecimal trOrigen;
     private String id_lado;
     private String rutaDocumentoWeb;

    public VehiculoDocumento() {
    }

   
    public String getIdVehiculo() {
        return this.id_vehiculo;
    }
    
    public void setIdVehiculo(String id) {
        this.id_vehiculo = id;
    }
    public String getRutaDocumento() {
        return this.rutaDocumento;
    }
    
    public void setRutaDocumento(String rutaDocumento) {
        this.rutaDocumento = rutaDocumento;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }
    
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }
    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }
    
    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }
    
    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }
    public BigDecimal getTrOrigen() {
        return this.trOrigen;
    }
    
    public void setTrOrigen(BigDecimal trOrigen) {
        this.trOrigen = trOrigen;
    }

    /**
     * @return the id_empresa
     */
    public String getId_empresa() {
        return id_empresa;
    }

    /**
     * @param id_empresa the id_empresa to set
     */
    public void setId_empresa(String id_empresa) {
        this.id_empresa = id_empresa;
    }

    /**
     * @return the id_tipo_trans
     */
    public String getId_tipo_trans() {
        return id_tipo_trans;
    }

    /**
     * @param id_tipo_trans the id_tipo_trans to set
     */
    public void setId_tipo_trans(String id_tipo_trans) {
        this.id_tipo_trans = id_tipo_trans;
    }

    /**
     * @return the id_documento
     */
    public String getId_documento() {
        return id_documento;
    }

    /**
     * @param id_documento the id_documento to set
     */
    public void setId_documento(String id_documento) {
        this.id_documento = id_documento;
    }

    /**
     * @return the id_lado
     */
    public String getId_lado() {
        return id_lado;
    }

    /**
     * @param id_lado the id_lado to set
     */
    public void setId_lado(String id_lado) {
        this.id_lado = id_lado;
    }

    /**
     * @return the rutaDocumentoWeb
     */
    public String getRutaDocumentoWeb() {
        return rutaDocumentoWeb;
    }

    /**
     * @param rutaDocumentoWeb the rutaDocumentoWeb to set
     */
    public void setRutaDocumentoWeb(String rutaDocumentoWeb) {
        this.rutaDocumentoWeb = rutaDocumentoWeb;
    }

}


